version: "3.9"

services:
  forge_spawn_service:
    environment:
      - FORGE_ENV=staging
      - BILLING_MODE=fake_charge
      - OPA_URL=http://forge_opa:8181
      - NATS_URL=nats://forge_nats:4222
      - MINIO_URL=http://forge_minio:9000
      - TEMPLATE_DIR=/templates
      - REDIS_URL=redis://forge_redis:6379
      - ORCHESTRATOR_URL=http://forge_orchestrator:8080
      - EGRESS_GATEWAY_URL=http://forge_egress_gateway:8089
      - SAT_HMAC_SECRET=${SAT_HMAC_SECRET}
    depends_on:
      - forge_opa
      - forge_nats
      - forge_minio
      - forge_redis

  forge_orchestrator:
    environment:
      - FORGE_ENV=staging
      - EGRESS_GATEWAY_URL=http://forge_egress_gateway:8089
      - ORCHESTRATOR_INTERNAL_TOKEN=${ORCHESTRATOR_INTERNAL_TOKEN}
      - OPERATOR_TOKEN=${OPERATOR_TOKEN}
      - SCOREBOARD_INTERNAL_TOKEN=${SCOREBOARD_INTERNAL_TOKEN}

  forge_scoreboard:
    environment:
      - FORGE_ENV=staging
      - EGRESS_GATEWAY_URL=http://forge_egress_gateway:8089
      - SCOREBOARD_INTERNAL_TOKEN=${SCOREBOARD_INTERNAL_TOKEN}

  forge_egress_gateway:
    environment:
      - DRY_RUN=false
