# compose.prod.yml
# Production overrides:
# - Expose ONLY via ingress (TLS termination + routing)
# - No direct host port publishing for internal services
# - Enforce required secrets via ${VAR:?required}
# - Disable dev escape hatches
# - Orchestrator runs ORCH_BACKEND=k8s (no docker.sock, no DOCKER_GID)

services:
  # ----------------------------
  # Ingress (ONLY thing with host ports)
  # ----------------------------
  forge_ingress:
    image: caddy:2.8.4-alpine
    container_name: forge_ingress
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      FORGE_DOMAIN: ${FORGE_DOMAIN:?required}
      FORGE_ACME_EMAIL: ${FORGE_ACME_EMAIL:?required}
    volumes:
      - ./telemetry/Caddyfile:/etc/caddy/Caddyfile:ro
      - forge_caddy_data:/data
      - forge_caddy_config:/config
    depends_on:
      forge_spawn_service:
        condition: service_started
      forge_egress_gateway:
        condition: service_started

  # ----------------------------
  # App strictness
  # ----------------------------
  forge_spawn_service:
    environment:
      FORGE_ENV: prod
      BILLING_MODE: ${BILLING_MODE:-stripe}

      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET:?required}
      SAT_HMAC_SECRET: ${SAT_HMAC_SECRET:?required}
      ET_HMAC_SECRET: ${ET_HMAC_SECRET:?required}
      RECEIPT_HMAC_SECRET: ${RECEIPT_HMAC_SECRET:?required}
      OPERATOR_TOKEN: ${OPERATOR_TOKEN:?required}

      # Disable dev escape hatches
      DEV_ALLOW_XPLAN: "false"
      DEV_ALLOW_MISSING_ET_SECRET: "false"
      ENTITLEMENT_ALLOW_ALL: "false"
      ALLOW_FREE_DEFAULT: "false"

      # Must be your real public base URL behind ingress
      SPAWN_BASE_URL: ${SPAWN_BASE_URL:?required}
      EGRESS_GATEWAY_PUBLIC_URL: ${EGRESS_GATEWAY_PUBLIC_URL:?required}
      CAP_TOKEN_SECRET: ${CAP_TOKEN_SECRET:?required}
      CAP_TOKEN_TTL_SECONDS: ${CAP_TOKEN_TTL_SECONDS:-300}
    ports: []

  forge_orchestrator:
    environment:
      FORGE_ENV: prod
      ORCH_BACKEND: k8s

      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET:?required}
      SAT_HMAC_SECRET: ${SAT_HMAC_SECRET:?required}
      OPERATOR_TOKEN: ${OPERATOR_TOKEN:?required}
      ORCHESTRATOR_INTERNAL_TOKEN: ${ORCHESTRATOR_INTERNAL_TOKEN:?required}
      SCOREBOARD_INTERNAL_TOKEN: ${SCOREBOARD_INTERNAL_TOKEN:?required}

      # Safety: prod should not touch host docker
      ALLOW_DOCKER_IN_PROD: "false"
    ports: []
    # Remove docker.sock access from base compose.yml
    volumes:
      - ./templates:/templates:ro
      - forge_orchestrator_storage:/app/storage
      - forge_orch_state:/data
    # Remove group_add that references ${DOCKER_GID} (kills the warning too)
    group_add: []

  forge_scoreboard:
    environment:
      FORGE_ENV: prod
      SCOREBOARD_INTERNAL_TOKEN: ${SCOREBOARD_INTERNAL_TOKEN:?required}
    ports: []

  forge_worker_agent:
    environment:
      FORGE_ENV: prod
    ports: []

  forge_overlay_sanitizer:
    environment:
      FORGE_ENV: prod
    ports: []

  forge_observer_hub:
    environment:
      FORGE_ENV: prod
    ports: []

  forge_playbook_runner:
    environment:
      FORGE_ENV: prod
    ports: []

  forge_metrics_tuner:
    environment:
      FORGE_ENV: prod
    ports: []

  forge_egress_gateway:
    environment:
      FORGE_ENV: prod
      CAP_TOKEN_SECRET: ${CAP_TOKEN_SECRET:?required}
      SAT_REQUIRED: "true"
      CAP_SINGLE_USE: "true"
      TTY_IDLE_SECONDS: ${TTY_IDLE_SECONDS:-900}
      TTY_MAX_SECONDS: ${TTY_MAX_SECONDS:-1800}
    ports: []

  forge_llm_analyzer:
    environment:
      FORGE_ENV: prod
    ports: []

  # ----------------------------
  # Infra strictness
  # ----------------------------
  forge_redis:
    ports: []

  forge_nats:
    ports: []

  forge_minio:
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:?required}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?required}
    ports: []

  forge_opa:
    ports: []

  forge_loki:
    ports: []

  forge_prometheus:
    ports: []

  forge_grafana:
    ports: []

volumes:
  forge_caddy_data:
  forge_caddy_config:
