# compose.staging.yml
# Staging overrides:
# - Disable published app ports (compose.expose.yml controls exposure)
# - Enforce required secrets/tokens
# - Add MinIO readiness gate (probe sharing MinIO netns)
# - Fix scoreboard volume permissions via one-shot job

services:
  forge_spawn_service:
    environment:
      BILLING_MODE: stripe
      SAT_HMAC_SECRET: ${SAT_HMAC_SECRET:?required}
    ports: []

  forge_orchestrator:
    environment:
      ORCHESTRATOR_INTERNAL_TOKEN: ${ORCHESTRATOR_INTERNAL_TOKEN:?required}
      OPERATOR_TOKEN: ${OPERATOR_TOKEN:?required}
      SCOREBOARD_INTERNAL_TOKEN: ${SCOREBOARD_INTERNAL_TOKEN:?required}
      SAT_HMAC_SECRET: ${SAT_HMAC_SECRET:?required}
    ports: []

  forge_scoreboard_storage_fix:
    image: alpine:3.19
    command: ["sh", "-lc", "chown -R 1000:1000 /data && ls -ld /data"]
    volumes:
      - forge_scoreboard_storage:/data
    restart: "no"

  forge_scoreboard:
    environment:
      SCOREBOARD_INTERNAL_TOKEN: ${SCOREBOARD_INTERNAL_TOKEN:?required}
    user: "1000:1000"
    ports: []
    depends_on:
      forge_scoreboard_storage_fix:
        condition: service_completed_successfully
      forge_minio_probe:
        condition: service_healthy

  forge_worker_agent:
    ports: []
    depends_on:
      forge_minio_probe:
        condition: service_healthy

  forge_overlay_sanitizer:
    ports: []
    depends_on:
      forge_minio_probe:
        condition: service_healthy

  forge_observer_hub: { ports: [] }
  forge_playbook_runner: { ports: [] }
  forge_metrics_tuner: { ports: [] }
  forge_egress_gateway: { ports: [] }
  forge_llm_analyzer: { ports: [] }

  # staging-only MinIO readiness gate (shares MinIO network namespace)
  forge_minio_probe:
    image: curlimages/curl:8.5.0
    command: ["sh", "-lc", "sleep infinity"]
    restart: unless-stopped
    depends_on:
      forge_minio:
        condition: service_started
    network_mode: "service:forge_minio"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:9000/minio/health/live >/dev/null || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 60
      start_period: 30s

volumes:
  forge_scoreboard_storage: {}
